# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: triplermodule.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='triplermodule.proto',
  package='triplermodule',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13triplermodule.proto\x12\rtriplermodule\"\x1a\n\rTripleRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\" \n\x0eTripleResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32X\n\rTriplerModule\x12G\n\x06Triple\x12\x1c.triplermodule.TripleRequest\x1a\x1d.triplermodule.TripleResponse\"\x00\x62\x06proto3'
)




_TRIPLEREQUEST = _descriptor.Descriptor(
  name='TripleRequest',
  full_name='triplermodule.TripleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='triplermodule.TripleRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=64,
)


_TRIPLERESPONSE = _descriptor.Descriptor(
  name='TripleResponse',
  full_name='triplermodule.TripleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='triplermodule.TripleResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['TripleRequest'] = _TRIPLEREQUEST
DESCRIPTOR.message_types_by_name['TripleResponse'] = _TRIPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TripleRequest = _reflection.GeneratedProtocolMessageType('TripleRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRIPLEREQUEST,
  '__module__' : 'triplermodule_pb2'
  # @@protoc_insertion_point(class_scope:triplermodule.TripleRequest)
  })
_sym_db.RegisterMessage(TripleRequest)

TripleResponse = _reflection.GeneratedProtocolMessageType('TripleResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRIPLERESPONSE,
  '__module__' : 'triplermodule_pb2'
  # @@protoc_insertion_point(class_scope:triplermodule.TripleResponse)
  })
_sym_db.RegisterMessage(TripleResponse)



_TRIPLERMODULE = _descriptor.ServiceDescriptor(
  name='TriplerModule',
  full_name='triplermodule.TriplerModule',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=100,
  serialized_end=188,
  methods=[
  _descriptor.MethodDescriptor(
    name='Triple',
    full_name='triplermodule.TriplerModule.Triple',
    index=0,
    containing_service=None,
    input_type=_TRIPLEREQUEST,
    output_type=_TRIPLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRIPLERMODULE)

DESCRIPTOR.services_by_name['TriplerModule'] = _TRIPLERMODULE

# @@protoc_insertion_point(module_scope)
