# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doublermodule.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='doublermodule.proto',
  package='doublermodule',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13\x64oublermodule.proto\x12\rdoublermodule\"\x1a\n\rDoubleRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\" \n\x0e\x44oubleResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32X\n\rDoublerModule\x12G\n\x06\x44ouble\x12\x1c.doublermodule.DoubleRequest\x1a\x1d.doublermodule.DoubleResponse\"\x00\x62\x06proto3'
)




_DOUBLEREQUEST = _descriptor.Descriptor(
  name='DoubleRequest',
  full_name='doublermodule.DoubleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='doublermodule.DoubleRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=64,
)


_DOUBLERESPONSE = _descriptor.Descriptor(
  name='DoubleResponse',
  full_name='doublermodule.DoubleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='doublermodule.DoubleResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['DoubleRequest'] = _DOUBLEREQUEST
DESCRIPTOR.message_types_by_name['DoubleResponse'] = _DOUBLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoubleRequest = _reflection.GeneratedProtocolMessageType('DoubleRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEREQUEST,
  '__module__' : 'doublermodule_pb2'
  # @@protoc_insertion_point(class_scope:doublermodule.DoubleRequest)
  })
_sym_db.RegisterMessage(DoubleRequest)

DoubleResponse = _reflection.GeneratedProtocolMessageType('DoubleResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLERESPONSE,
  '__module__' : 'doublermodule_pb2'
  # @@protoc_insertion_point(class_scope:doublermodule.DoubleResponse)
  })
_sym_db.RegisterMessage(DoubleResponse)



_DOUBLERMODULE = _descriptor.ServiceDescriptor(
  name='DoublerModule',
  full_name='doublermodule.DoublerModule',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=100,
  serialized_end=188,
  methods=[
  _descriptor.MethodDescriptor(
    name='Double',
    full_name='doublermodule.DoublerModule.Double',
    index=0,
    containing_service=None,
    input_type=_DOUBLEREQUEST,
    output_type=_DOUBLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOUBLERMODULE)

DESCRIPTOR.services_by_name['DoublerModule'] = _DOUBLERMODULE

# @@protoc_insertion_point(module_scope)
